

image: python:3.10.5-slim

before_script:
  - python -V

stages:
  - build
  - lint
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "No venv required"
    - echo "Each stage starts its own docker instance"
    - echo "This step intended to produce build artifacts"
    - echo "Then ship the artifacts to a location shared between stages"

lint-job:
  stage: lint
  script:
    - pip install -r requirements.txt
    - echo "Linting unit tests..."
    - pylint --disable=F0401 tests/*.py
    - echo "Linting features..."
    - pylint --disable=W0107 features/*.py

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    - pip install -r requirements.txt
    - PYTHONPATH=. coverage run -m pytest tests/test_*.py
    - RESULT=$(PYTHONPATH=. coverage report -m | grep TOTAL | sed 's/%//g')
    - read -a strarr <<< "$RESULT"
    - COV="${strarr[3]}"
    - echo "Code coverage is $COV%"
    - if [ "$COV" -lt 80 ]; then echo "Code coverage insufficient" && exit 1; fi

feature-test-job:
  stage: test
  script:
    - echo "Running feature tests..."
    - pip install -r requirements.txt
    - PYTHONPATH=. coverage run -m pytest features/test_*.py
    - RESULT=$(PYTHONPATH=. coverage report -m | grep TOTAL | sed 's/%//g')
    - read -a strarr <<< "$RESULT"
    - COV="${strarr[3]}"
    - echo "Code coverage is $COV%"
    - if [ "$COV" -lt 80 ]; then echo "Code coverage insufficient" && exit 1; fi

deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Place deployment code here"
